export const numberOperand = [
  { id: 1, context: "C", type: "function" },
  { id: 2, context: "7" },
  { id: 3, context: "8" },
  { id: 4, context: "9" },
  { id: 5, context: "*", type: "operation" },
  { id: 6, context: "-", type: "operation" },
  { id: 7, context: "4" },
  { id: 8, context: "5" },
  { id: 9, context: "6" },
  { id: 10, context: "/", type: "operation" },
  { id: 11, context: "+", type: "operation" },
  { id: 12, context: "1" },
  { id: 13, context: "2" },
  { id: 14, context: "3" },
  { id: 15, context: "=", type: "operation" },
  { id: 16, context: "." },
  { id: 17, context: "%", type: "operation" },
  { id: 18, context: "0" },
  { id: 19, context: "^", type: "operation" },
  { id: 20, context: "CE", type: "function" },
];
